[project]
name = "default"
master = "cvm"
common_modules = ["core", "tm", "pvu", "fwt", "exc", "clk"]
mcc_id = 0
module_dirs = [
  "subprojects/photon/modules/photon/core",
  "subprojects/photon/modules/photon/tm",
  "subprojects/photon/modules/photon/fwt",
  "subprojects/photon/modules/photon/pvu",
  "subprojects/photon/modules/photon/test",
  "subprojects/photon/modules/photon/exc",
  "subprojects/photon/modules/photon/clk",
  "subprojects/photon/modules/photon/nav",
  "subprojects/photon/modules/photon/fl",
  "subprojects/photon/modules/photon/grp",
  "modules/aerobot/udp",
  "modules/photon/px4",
  "modules/photon/px4_autogen",
  "modules/photon/usm",
]

[[devices]]
name = "cvm"
id = 1
cmd_targets = ["cvm"]
tm_sources = ["cvm"]
modules = ["test", "nav", "fl", "udp", "grp", "px4", "px4_autogen", "usm"]

[[devices]]
name = "fcu"
id = 2
cmd_targets = ["fcu"]
tm_sources = ["fcu"]
modules = ["test", "nav"]

