[project]
name = "default"
master = "cvm"
common_modules = ["core", "tm", "int", "fwt", "exc"]
mcc_id = 0
module_dirs = [
  "thirdparty/photon/modules/photon/core",
  "thirdparty/photon/modules/photon/tm",
  "thirdparty/photon/modules/photon/fwt",
  "thirdparty/photon/modules/photon/int",
  "thirdparty/photon/modules/photon/test",
  "thirdparty/photon/modules/photon/exc",
  "modules/photon/esc",
]

[[devices]]
name = "cvm"
id = 1
cmd_targets = ["esc"]
tm_sources = ["esc"]
modules = ["test"]

[[devices]]
name = "esc"
id = 2

