[project]
name = "default"
master = "cvm"
common_modules = ["core", "tm", "pvu", "fwt", "exc", "clk"]
mcc_id = 0
module_dirs = [
  "thirdparty/photon/modules/photon/asv",
  "thirdparty/photon/modules/photon/core",
  "thirdparty/photon/modules/photon/tm",
  "thirdparty/photon/modules/photon/fwt",
  "thirdparty/photon/modules/photon/pvu",
  "thirdparty/photon/modules/photon/dfu",
  "thirdparty/photon/modules/photon/test",
  "thirdparty/photon/modules/photon/exc",
  "thirdparty/photon/modules/photon/clk",
  "thirdparty/photon/modules/photon/nav",
  "thirdparty/photon/modules/photon/fl",
  "thirdparty/photon/modules/photon/grp",
  "thirdparty/photon/modules/photon/usm",
  "modules/aerobot/udp",
  "modules/photon/px4_autogen",
  "modules/photon/powercom",
  "modules/photon/powerfan",
  "modules/photon/powerfanproxy",
  "modules/photon/zcvm",
  "modules/photon/ximea",
  "modules/photon/zlidar",
]

[component_numbers]
asv = 0
clk = 1
core = 2
exc = 3
fl = 4
fwt = 5
grp = 6
nav = 7
powercom = 8
powerfan = 9
powerfanproxy = 10
pvu = 11
px4 = 12
px4_autogen = 13
test = 14
tm = 15
udp = 16
usm = 17
ximea = 18
zcvm = 19
zlidar = 20
dfu = 21
fcu = 22

[[devices]]
name = "cvm"
id = 1
cmd_targets = ["cvm", "powerfan1", "powerfan2"]
tm_sources = ["cvm", "powerfan1", "powerfan2"]
modules = ["test", "nav", "fl", "udp", "grp", "px4_autogen", "usm", "powercom", "powerfanproxy", "zcvm", "ximea", "zlidar", "asv"]

[[devices]]
name = "fcu"
id = 2
cmd_targets = ["fcu"]
tm_sources = ["fcu"]
modules = ["test", "nav"]

[[devices]]
name = "powercom"
id = 3
modules = ["powercom"]

[[devices]]
name = "powerfan1"
id = 4
modules = ["powerfan", "asv"]

[[devices]]
name = "powerfan2"
id = 5
modules = ["powerfan", "asv"]

