[project]
name = "default"
master = "cvm"
common_modules = ["core", "tm", "pvu", "fwt", "exc", "clk"]
mcc_id = 0
module_dirs = [
  "thirdparty/photon/modules/photon/core",
  "thirdparty/photon/modules/photon/tm",
  "thirdparty/photon/modules/photon/fwt",
  "thirdparty/photon/modules/photon/pvu",
  "thirdparty/photon/modules/photon/test",
  "thirdparty/photon/modules/photon/exc",
  "thirdparty/photon/modules/photon/clk",
  "thirdparty/photon/modules/photon/nav",
  "thirdparty/photon/modules/photon/fl",
  "thirdparty/photon/modules/photon/grp",
  "thirdparty/photon/modules/photon/usm",
  "modules/aerobot/udp",
  "modules/photon/px4",
  "modules/photon/px4_autogen",
  "modules/photon/powercom",
  "modules/photon/powerfan",
  "modules/photon/powerfanproxy",
]

[[devices]]
name = "cvm"
id = 1
cmd_targets = ["cvm", "powerfan1", "powerfan2"]
tm_sources = ["cvm"]
modules = ["test", "nav", "fl", "udp", "grp", "px4", "px4_autogen", "usm", "powercom", "powerfanproxy"]

[[devices]]
name = "fcu"
id = 2
cmd_targets = ["fcu"]
tm_sources = ["fcu"]
modules = ["test", "nav"]

[[devices]]
name = "powercom"
id = 3
modules = ["powercom"]

[[devices]]
name = "powerfan1"
id = 4
modules = ["powerfan"]

[[devices]]
name = "powerfan2"
id = 5
modules = ["powerfan"]

